
name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - main  # ou gh-pages, selon votre configuration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x' # ou la version de Ruby que vous utilisez
          bundler-cache: true # Cache les dépendances pour accélérer les builds

      - name: Build with Jekyll
        run: bundle exec jekyll build --source ./docs --destination ./docs/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
